/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vrs.projetovrs.view;

import com.vrs.projetovrs.dao.VendaDao;
import com.vrs.projetovrs.model.status.Status;

import javax.swing.*;

/**
 * @author Rubens
 */
public class HistoricoVendasDetalhadaView extends javax.swing.JFrame {

    public Integer idVenda;

    /**
     * Creates new form HistoricoVendasView
     */
    public HistoricoVendasDetalhadaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTituloHistoricoVendas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelSelecaoDatasHistoricoVendasDetalhada = new javax.swing.JPanel();
        campoDataHistoricoVendaDetalhada = new javax.swing.JLabel();
        campoTotalHistoricoVendaDetalhada = new javax.swing.JLabel();
        textoTotalHistoricoVendaDetalhada = new javax.swing.JTextField();
        campoClienteHistoricoVendaDetalhada = new javax.swing.JLabel();
        textoClienteHistoricoVendaDetalhada = new javax.swing.JTextField();
        textoDataHistoricoVendaDetalhada = new javax.swing.JTextField();
        botaoEstornarVendaDetalhesVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItensVendidosHistoricoVendasDetalhada = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes da Venda");

        painelTituloHistoricoVendas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Detalhes da Venda");

        javax.swing.GroupLayout painelTituloHistoricoVendasLayout = new javax.swing.GroupLayout(painelTituloHistoricoVendas);
        painelTituloHistoricoVendas.setLayout(painelTituloHistoricoVendasLayout);
        painelTituloHistoricoVendasLayout.setHorizontalGroup(
            painelTituloHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloHistoricoVendasLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTituloHistoricoVendasLayout.setVerticalGroup(
            painelTituloHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloHistoricoVendasLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        painelSelecaoDatasHistoricoVendasDetalhada.setBackground(new java.awt.Color(102, 102, 102));
        painelSelecaoDatasHistoricoVendasDetalhada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        campoDataHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDataHistoricoVendaDetalhada.setForeground(new java.awt.Color(255, 255, 255));
        campoDataHistoricoVendaDetalhada.setText("Data");
        campoDataHistoricoVendaDetalhada.setBorder(new javax.swing.border.MatteBorder(null));

        campoTotalHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTotalHistoricoVendaDetalhada.setForeground(new java.awt.Color(255, 255, 255));
        campoTotalHistoricoVendaDetalhada.setText("Total da Venda");
        campoTotalHistoricoVendaDetalhada.setBorder(new javax.swing.border.MatteBorder(null));

        textoTotalHistoricoVendaDetalhada.setEditable(false);
        textoTotalHistoricoVendaDetalhada.setBackground(new java.awt.Color(255, 255, 255));
        textoTotalHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoTotalHistoricoVendaDetalhada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoTotalHistoricoVendaDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTotalHistoricoVendaDetalhadaActionPerformed(evt);
            }
        });
        textoTotalHistoricoVendaDetalhada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoTotalHistoricoVendaDetalhadaKeyPressed(evt);
            }
        });

        campoClienteHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoClienteHistoricoVendaDetalhada.setForeground(new java.awt.Color(255, 255, 255));
        campoClienteHistoricoVendaDetalhada.setText("Cliente");
        campoClienteHistoricoVendaDetalhada.setBorder(new javax.swing.border.MatteBorder(null));

        textoClienteHistoricoVendaDetalhada.setEditable(false);
        textoClienteHistoricoVendaDetalhada.setBackground(new java.awt.Color(255, 255, 255));
        textoClienteHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoClienteHistoricoVendaDetalhada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoClienteHistoricoVendaDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClienteHistoricoVendaDetalhadaActionPerformed(evt);
            }
        });
        textoClienteHistoricoVendaDetalhada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoClienteHistoricoVendaDetalhadaKeyPressed(evt);
            }
        });

        textoDataHistoricoVendaDetalhada.setEditable(false);
        textoDataHistoricoVendaDetalhada.setBackground(new java.awt.Color(255, 255, 255));
        textoDataHistoricoVendaDetalhada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoDataHistoricoVendaDetalhada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoDataHistoricoVendaDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataHistoricoVendaDetalhadaActionPerformed(evt);
            }
        });
        textoDataHistoricoVendaDetalhada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDataHistoricoVendaDetalhadaKeyPressed(evt);
            }
        });

        botaoEstornarVendaDetalhesVenda.setText("Estornar essa venda");
        botaoEstornarVendaDetalhesVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstornarVendaDetalhesVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSelecaoDatasHistoricoVendasDetalhadaLayout = new javax.swing.GroupLayout(painelSelecaoDatasHistoricoVendasDetalhada);
        painelSelecaoDatasHistoricoVendasDetalhada.setLayout(painelSelecaoDatasHistoricoVendasDetalhadaLayout);
        painelSelecaoDatasHistoricoVendasDetalhadaLayout.setHorizontalGroup(
            painelSelecaoDatasHistoricoVendasDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createSequentialGroup()
                        .addComponent(campoClienteHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoClienteHistoricoVendaDetalhada))
                    .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createSequentialGroup()
                        .addComponent(campoDataHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDataHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(campoTotalHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoTotalHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(botaoEstornarVendaDetalhesVenda)
                .addGap(22, 22, 22))
        );
        painelSelecaoDatasHistoricoVendasDetalhadaLayout.setVerticalGroup(
            painelSelecaoDatasHistoricoVendasDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSelecaoDatasHistoricoVendasDetalhadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotalHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTotalHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDataHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(painelSelecaoDatasHistoricoVendasDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoClienteHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoClienteHistoricoVendaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEstornarVendaDetalhesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        tabelaItensVendidosHistoricoVendasDetalhada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Preço", "Subtotal Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaItensVendidosHistoricoVendasDetalhada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTituloHistoricoVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelSelecaoDatasHistoricoVendasDetalhada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTituloHistoricoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelSelecaoDatasHistoricoVendasDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoTotalHistoricoVendaDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTotalHistoricoVendaDetalhadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTotalHistoricoVendaDetalhadaActionPerformed

    private void textoTotalHistoricoVendaDetalhadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTotalHistoricoVendaDetalhadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTotalHistoricoVendaDetalhadaKeyPressed

    private void textoClienteHistoricoVendaDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClienteHistoricoVendaDetalhadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClienteHistoricoVendaDetalhadaActionPerformed

    private void textoClienteHistoricoVendaDetalhadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoClienteHistoricoVendaDetalhadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClienteHistoricoVendaDetalhadaKeyPressed

    private void textoDataHistoricoVendaDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataHistoricoVendaDetalhadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataHistoricoVendaDetalhadaActionPerformed

    private void textoDataHistoricoVendaDetalhadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDataHistoricoVendaDetalhadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataHistoricoVendaDetalhadaKeyPressed

    /**
     * Este método é acionado quando o botão "Estornar Venda" é clicado na janela de detalhes da venda.
     * Ele realiza o estorno de uma venda com base no ID da venda e atualiza o status da venda para "DIGITANDO".
     * Também exibe uma mensagem de sucesso ao usuário.
     */
    private void botaoEstornarVendaDetalhesVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstornarVendaDetalhesVendaActionPerformed
        // TODO add your handling code here:
        VendaDao vendaDao = new VendaDao();
        vendaDao.estornarVendaPorId(this.idVenda, Status.DIGITANDO);
        JOptionPane.showMessageDialog(null, "Venda com id " + this.idVenda + " estornada com sucesso");

    }//GEN-LAST:event_botaoEstornarVendaDetalhesVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasDetalhadaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasDetalhadaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasDetalhadaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasDetalhadaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoVendasDetalhadaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEstornarVendaDetalhesVenda;
    private javax.swing.JLabel campoClienteHistoricoVendaDetalhada;
    private javax.swing.JLabel campoDataHistoricoVendaDetalhada;
    private javax.swing.JLabel campoTotalHistoricoVendaDetalhada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelSelecaoDatasHistoricoVendasDetalhada;
    private javax.swing.JPanel painelTituloHistoricoVendas;
    public javax.swing.JTable tabelaItensVendidosHistoricoVendasDetalhada;
    public javax.swing.JTextField textoClienteHistoricoVendaDetalhada;
    public javax.swing.JTextField textoDataHistoricoVendaDetalhada;
    public javax.swing.JTextField textoTotalHistoricoVendaDetalhada;
    // End of variables declaration//GEN-END:variables
}
