/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vrs.projetovrs.view;

import com.vrs.projetovrs.dao.ProdutoDao;
import com.vrs.projetovrs.exception.ValidationException;
import com.vrs.projetovrs.model.Produto;
import com.vrs.projetovrs.util.Utilities;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;

/**
 * @author Rubens
 */
public class ProdutoView extends javax.swing.JFrame {

    /**
     * variável global que é determinada de acordo com um produto selecionado na 'tabelaExibicaoProdutos'
     * tendo armazenado o id de determinado registro, podemos executar os métodos de excluir e editar registros
     */
    private Integer idSelecionado;

    // Enum para representar o estado atual da janela (INICIAL, NOVO, EDITANDO)
    private enum Estado { INICIAL, NOVO, EDITANDO }

    private Estado estadoAtual;

    private void gerenciadorDeBotoes() {
        switch (estadoAtual) {
            case INICIAL:
                botaoNovo.setEnabled(true);
                botaoSalvar.setEnabled(false);
                botaoEditar.setEnabled(false);
                botaoExcluir.setEnabled(false);
                botaoLimpar.setEnabled(false);
                textoDescricao.setEditable(false);
                textoDescricao.setBackground(Color.LIGHT_GRAY);
                textoPreco.setEditable(false);
                textoPreco.setBackground(Color.LIGHT_GRAY);
                textoQuantidade.setEditable(false);
                textoQuantidade.setBackground(Color.LIGHT_GRAY);
                break;
            case NOVO:
                painelComAbasProduto.setSelectedIndex(0);
                botaoNovo.setEnabled(false);
                botaoSalvar.setEnabled(true);
                botaoEditar.setEnabled(false);
                botaoExcluir.setEnabled(false);
                botaoLimpar.setEnabled(true);
                textoDescricao.setEditable(true);
                textoDescricao.setBackground(Color.WHITE);
                textoPreco.setText(BigDecimal.ZERO.toString());
                textoPreco.setEditable(true);
                textoPreco.setBackground(Color.WHITE);
                textoQuantidade.setEditable(true);
                textoQuantidade.setBackground(Color.WHITE);
                break;
            case EDITANDO:
                botaoNovo.setEnabled(false);
                botaoSalvar.setEnabled(false);
                botaoEditar.setEnabled(true);
                botaoExcluir.setEnabled(true);
                botaoLimpar.setEnabled(true);
                textoDescricao.setEditable(true);
                textoDescricao.setBackground(Color.WHITE);
                textoPreco.setEditable(true);
                textoPreco.setBackground(Color.WHITE);
                textoQuantidade.setEditable(true);
                textoQuantidade.setBackground(Color.WHITE);
                break;
            default:

        }
    }

    /**
     * lista todos os produtos registrados no banco de dados na tabela de visualização de produtos (tabelaExibicaoProdutos)
     */
    public void listarProdutosNaTabela() {
        ProdutoDao dao = new ProdutoDao();
        List<Produto> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) tabelaExibicaoProdutos.getModel();
        dados.setNumRows(0);
        for (Produto produto : lista) {
            dados.addRow(new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    "R$ " + produto.getPreco(),
                    produto.getQuandidade()
            });
        }
    }

    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        initComponents();
        setLocationRelativeTo(null);
        estadoAtual = Estado.INICIAL;
        gerenciadorDeBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelComAbasProduto = new javax.swing.JTabbedPane();
        painelDadosProduto = new javax.swing.JPanel();
        campoDescricaoProduto = new javax.swing.JLabel();
        textoQuantidade = new javax.swing.JTextField();
        campoQuantidadeProduto = new javax.swing.JLabel();
        textoDescricao = new javax.swing.JTextField();
        campoPrecoProduto = new javax.swing.JLabel();
        textoPreco = new javax.swing.JTextField();
        painelConsultaProdutos = new javax.swing.JPanel();
        campoNomePesquisaProduto = new javax.swing.JLabel();
        textoDescricaoPesquisaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaExibicaoProdutos = new javax.swing.JTable();
        botaoPesquisarProduto = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Consulta Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51))
        );

        painelComAbasProduto.setBackground(new java.awt.Color(255, 255, 255));
        painelComAbasProduto.setForeground(new java.awt.Color(0, 0, 0));

        painelDadosProduto.setBackground(new java.awt.Color(204, 204, 204));

        campoDescricaoProduto.setBackground(new java.awt.Color(204, 204, 204));
        campoDescricaoProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDescricaoProduto.setForeground(new java.awt.Color(0, 0, 0));
        campoDescricaoProduto.setText("Descrição");
        campoDescricaoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        textoQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQuantidadeActionPerformed(evt);
            }
        });

        campoQuantidadeProduto.setBackground(new java.awt.Color(204, 204, 204));
        campoQuantidadeProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoQuantidadeProduto.setForeground(new java.awt.Color(0, 0, 0));
        campoQuantidadeProduto.setText("Quantidade (estoque)");
        campoQuantidadeProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoDescricao.setBackground(new java.awt.Color(255, 255, 255));
        textoDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDescricaoActionPerformed(evt);
            }
        });

        campoPrecoProduto.setBackground(new java.awt.Color(204, 204, 204));
        campoPrecoProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoPrecoProduto.setForeground(new java.awt.Color(0, 0, 0));
        campoPrecoProduto.setText("Preço: ");
        campoPrecoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoPreco.setBackground(new java.awt.Color(255, 255, 255));
        textoPreco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosProdutoLayout = new javax.swing.GroupLayout(painelDadosProduto);
        painelDadosProduto.setLayout(painelDadosProdutoLayout);
        painelDadosProdutoLayout.setHorizontalGroup(
                painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                                                .addComponent(campoDescricaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                                                .addComponent(campoPrecoProduto)
                                                .addGap(18, 18, 18)
                                                .addComponent(textoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(campoQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        painelDadosProdutoLayout.setVerticalGroup(
                painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(286, Short.MAX_VALUE))
        );

        painelComAbasProduto.addTab("Cadastro/Manutenção Produtos", painelDadosProduto);

        painelConsultaProdutos.setBackground(new java.awt.Color(204, 204, 204));

        campoNomePesquisaProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoNomePesquisaProduto.setForeground(new java.awt.Color(0, 0, 0));
        campoNomePesquisaProduto.setText("Descrição");
        campoNomePesquisaProduto.setBorder(new javax.swing.border.MatteBorder(null));

        textoDescricaoPesquisaProduto.setBackground(new java.awt.Color(255, 255, 255));
        textoDescricaoPesquisaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoDescricaoPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDescricaoPesquisaProdutoActionPerformed(evt);
            }
        });
        textoDescricaoPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDescricaoPesquisaProdutoKeyPressed(evt);
            }
        });

        tabelaExibicaoProdutos.setBackground(new java.awt.Color(255, 255, 255));
        tabelaExibicaoProdutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaExibicaoProdutos.setForeground(new java.awt.Color(0, 0, 0));
        tabelaExibicaoProdutos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Identificador", "Descrição", "Preço", "Qtd. Estoque"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabelaExibicaoProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaExibicaoProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaExibicaoProdutos);

        botaoPesquisarProduto.setBackground(new java.awt.Color(255, 255, 255));
        botaoPesquisarProduto.setForeground(new java.awt.Color(0, 0, 0));
        botaoPesquisarProduto.setText("Pesquisar");
        botaoPesquisarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaProdutosLayout = new javax.swing.GroupLayout(painelConsultaProdutos);
        painelConsultaProdutos.setLayout(painelConsultaProdutosLayout);
        painelConsultaProdutosLayout.setHorizontalGroup(
                painelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelConsultaProdutosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(campoNomePesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoDescricaoPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(115, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)
        );
        painelConsultaProdutosLayout.setVerticalGroup(
                painelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaProdutosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelConsultaProdutosLayout.createSequentialGroup()
                                                .addComponent(campoNomePesquisaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(1, 1, 1))
                                        .addGroup(painelConsultaProdutosLayout.createSequentialGroup()
                                                .addGroup(painelConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(textoDescricaoPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );

        painelComAbasProduto.addTab("Consulta de Produtos", painelConsultaProdutos);

        botaoEditar.setText("EDITAR");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("SALVAR");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoNovo.setText("NOVO");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoLimpar.setText("LIMPAR");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoExcluir.setText("EXCLUIR");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelComAbasProduto)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{botaoEditar, botaoLimpar, botaoNovo, botaoSalvar});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(painelComAbasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{botaoEditar, botaoLimpar, botaoNovo, botaoSalvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoQuantidadeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista de produtos na tela de busca produtos
        listarProdutosNaTabela();
    }//GEN-LAST:event_formWindowActivated

    private void textoDescricaoPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDescricaoPesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescricaoPesquisaProdutoActionPerformed

    /**
     * executa a busca de produtos no banco de dados de acordo com os caracteres na descricao, retornando na tabela de exibição de produtos registrados.
     *
     * @param evt
     */
    private void botaoPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarProdutoActionPerformed
        String nomeDesejado = textoDescricaoPesquisaProduto.getText();

        ProdutoDao dao = new ProdutoDao();
        List<Produto> lista = dao.listarProdutosPorNome(nomeDesejado);
        DefaultTableModel dados = (DefaultTableModel) tabelaExibicaoProdutos.getModel();
        dados.setNumRows(0);
        for (Produto produto : lista) {
            dados.addRow(new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    produto.getPreco(),
                    produto.getQuandidade()
            });
        }
    }//GEN-LAST:event_botaoPesquisarProdutoActionPerformed

    private void textoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescricaoActionPerformed

    private void textoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrecoActionPerformed

    /**
     * faz uma busca instantânea ao por produtos que tenham na descrição os caracteres inseridos no campo de busca
     * da aba consulta produtos
     *
     * @param evt
     */
    private void textoDescricaoPesquisaProdutoKeyPressed(java.awt.event.KeyEvent evt) {
        String nomeDesejado = textoDescricaoPesquisaProduto.getText();
        ProdutoDao dao = new ProdutoDao();
        List<Produto> lista = dao.listarProdutosPorNome(nomeDesejado);
        DefaultTableModel dados = (DefaultTableModel) tabelaExibicaoProdutos.getModel();
        dados.setNumRows(0);
        for (Produto produto : lista) {
            dados.addRow(new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    "R$ " + produto.getPreco(),
                    produto.getQuandidade()
            });
        }
    }

    /**
     * seleciona determinado produto na 'tabelaExibicaoProdutos' e preenche os campos 'textoDescricao', 'textoPreco' e 'textoQuantidade' na janela 'dados do produto'
     * de modo que o usuário possa editar ou excluir este mesmo produto
     *
     * @param evt
     */
    private void tabelaExibicaoProdutosMouseClicked(java.awt.event.MouseEvent evt) {
        painelComAbasProduto.setSelectedIndex(0);
        this.idSelecionado = Integer.parseInt(tabelaExibicaoProdutos.getValueAt(tabelaExibicaoProdutos.getSelectedRow(), 0).toString());
        textoDescricao.setText(tabelaExibicaoProdutos.getValueAt(tabelaExibicaoProdutos.getSelectedRow(), 1).toString());
        textoPreco.setText(tabelaExibicaoProdutos.getValueAt(tabelaExibicaoProdutos.getSelectedRow(), 2).toString().replace("R$ ", ""));
        textoQuantidade.setText(tabelaExibicaoProdutos.getValueAt(tabelaExibicaoProdutos.getSelectedRow(), 3).toString());
        estadoAtual = Estado.EDITANDO;
        gerenciadorDeBotoes();
    }

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        // TODO add your handling code here:
        estadoAtual = Estado.NOVO;
        gerenciadorDeBotoes();
    }//GEN-LAST:event_botaoNovoActionPerformed

    /**
     * realiza a chamada de uma sequência de métodos responsáveis por salvar um novo registro no banco de dados
     *
     * @param evt
     */
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String descricao = textoDescricao.getText();
            BigDecimal preco = new BigDecimal(textoPreco.getText().replace(",", "."));
            Integer quantidade = Integer.parseInt(textoQuantidade.getText());

            validarCampos(descricao, preco, quantidade);

            Produto produto = new Produto();
            produto.setDescricao(descricao);
            produto.setPreco(preco);
            produto.setQuandidade(quantidade);

            ProdutoDao dao = new ProdutoDao();
            dao.cadastrarProduto(produto);

            new Utilities().limpaCampos(painelDadosProduto);
            estadoAtual = Estado.INICIAL;
            gerenciadorDeBotoes();
        } catch (NumberFormatException | ValidationException ex) {
            JOptionPane.showMessageDialog(null, "Digite valores válidos para descrição, preço e quantidade");
        }
    }

    /**
     * realiza a chamada de uma sequência de métodos responsáveis pela edição de um registro presente no banco de dados
     *
     * @param evt
     */
    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (this.idSelecionado != null) {
                String descricao = textoDescricao.getText();
                BigDecimal preco = new BigDecimal(textoPreco.getText().replace(",", "."));
                Integer quantidade = Integer.parseInt(textoQuantidade.getText());

                validarCampos(descricao, preco, quantidade);

                Produto produto = new Produto();
                produto.setId(this.idSelecionado);
                produto.setDescricao(descricao);
                produto.setPreco(preco);
                produto.setQuandidade(quantidade);
                ProdutoDao dao = new ProdutoDao();
                dao.editarProduto(produto);

            }
            new Utilities().limpaCampos(painelDadosProduto);
            this.idSelecionado = null;
            estadoAtual = Estado.INICIAL;
            gerenciadorDeBotoes();
        } catch (NumberFormatException | ValidationException ex) {
            JOptionPane.showMessageDialog(null, "Digite valores válidos para descrição, preço e quantidade");
        }

    }

    /**
     * realiza a chamada de uma sequência de métodos responsáveis pela exclusão de um registro presente no banco de dados
     *
     * @param evt
     */
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.idSelecionado != null) {
            ProdutoDao dao = new ProdutoDao();
            dao.excluirProduto(idSelecionado);
        }
        new Utilities().limpaCampos(painelDadosProduto);
        this.idSelecionado = null;
        estadoAtual = Estado.INICIAL;
        gerenciadorDeBotoes();
    }

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {
        new Utilities().limpaCampos(painelDadosProduto);
        this.idSelecionado = null;
        estadoAtual = Estado.INICIAL;
        gerenciadorDeBotoes();
    }

    /**
     * valida os os valores inseridos nos campos de criação/ edição de um produto
     * caso o usuários coloque valores inválidos, definido no método, uma exceção é lançada
     * @param descricao
     * @param preco
     * @param quantidade
     * @throws ValidationException
     */
    private void validarCampos(String descricao, BigDecimal preco, Integer quantidade) throws ValidationException {
        if (descricao.isEmpty() || preco.compareTo(BigDecimal.ZERO) <= 0 || quantidade <= 0) {
            throw new ValidationException("Valores inválidos");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoPesquisarProduto;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel campoDescricaoProduto;
    private javax.swing.JLabel campoNomePesquisaProduto;
    private javax.swing.JLabel campoPrecoProduto;
    private javax.swing.JLabel campoQuantidadeProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane painelComAbasProduto;
    public javax.swing.JPanel painelConsultaProdutos;
    private javax.swing.JPanel painelDadosProduto;
    private javax.swing.JTable tabelaExibicaoProdutos;
    private javax.swing.JTextField textoDescricao;
    private javax.swing.JTextField textoDescricaoPesquisaProduto;
    private javax.swing.JTextField textoPreco;
    private javax.swing.JTextField textoQuantidade;
    // End of variables declaration//GEN-END:variables
}
