/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vrs.projetovrs.view;

import com.vrs.projetovrs.dao.ClienteDao;
import com.vrs.projetovrs.dao.ProdutoDao;
import com.vrs.projetovrs.model.Cliente;
import com.vrs.projetovrs.model.Produto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author Rubens
 */
public class VendaView extends javax.swing.JFrame {

    BigDecimal total = BigDecimal.ZERO;
    BigDecimal preco, subtotal;
    Integer quantidade;
    DefaultTableModel carrinhoDeComprasVendaView;
    Cliente clienteVendaView = new Cliente();

    /**
     * Creates new form ProdutoView
     */
    public VendaView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoPagamentoPdv = new javax.swing.JButton();
        botaoCancelarVendaPdv = new javax.swing.JButton();
        painelDadosProdutoPdv = new javax.swing.JPanel();
        campoNomeCadastro = new javax.swing.JLabel();
        textoDescricaoProdutoPdv = new javax.swing.JTextField();
        campoNomeCadastro1 = new javax.swing.JLabel();
        textoIdentificadorProdutoPdv = new javax.swing.JTextField();
        campoNomeCadastro4 = new javax.swing.JLabel();
        textoQuantidadeProdutoPdv = new javax.swing.JTextField();
        campoNomeCadastro5 = new javax.swing.JLabel();
        textoPrecoProdutoPdv = new javax.swing.JTextField();
        botaoAcicionarItemPdv = new javax.swing.JButton();
        botaoPesquisarProdutoPdv = new javax.swing.JButton();
        painelDadosClientePdv = new javax.swing.JPanel();
        campoNomeCadastro2 = new javax.swing.JLabel();
        textoIdentificadorClientePdv = new javax.swing.JTextField();
        campoNomeCadastro3 = new javax.swing.JLabel();
        textoNomeClientePdv = new javax.swing.JTextField();
        botaoPesquisarClientePdv = new javax.swing.JButton();
        campoIdentificadorClientePdv = new javax.swing.JLabel();
        textoDataPdv = new javax.swing.JTextField();
        painelCarrinhoDeComprasPdv = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        painelTotalVendaPdv = new javax.swing.JPanel();
        campoTotalVendaPdv = new javax.swing.JLabel();
        textoCampoTotalVendaPdv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Vendas PDV");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PDV - VR Software");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("A busca de cliente e produto é realizada por meio do número identificador de cada um deles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoPagamentoPdv.setText("PAGAMENTO");
        botaoPagamentoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPagamentoPdvActionPerformed(evt);
            }
        });

        botaoCancelarVendaPdv.setText("CANCELAR VENDA");
        botaoCancelarVendaPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVendaPdvActionPerformed(evt);
            }
        });

        painelDadosProdutoPdv.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosProdutoPdv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        campoNomeCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro.setText("Identificador");
        campoNomeCadastro.setBorder(new javax.swing.border.MatteBorder(null));

        textoDescricaoProdutoPdv.setEditable(false);
        textoDescricaoProdutoPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoDescricaoProdutoPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoDescricaoProdutoPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoDescricaoProdutoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDescricaoProdutoPdvActionPerformed(evt);
            }
        });
        textoDescricaoProdutoPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDescricaoProdutoPdvKeyPressed(evt);
            }
        });

        campoNomeCadastro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro1.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro1.setText("Descrição");
        campoNomeCadastro1.setBorder(new javax.swing.border.MatteBorder(null));

        textoIdentificadorProdutoPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoIdentificadorProdutoPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoIdentificadorProdutoPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoIdentificadorProdutoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIdentificadorProdutoPdvActionPerformed(evt);
            }
        });
        textoIdentificadorProdutoPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoIdentificadorProdutoPdvKeyPressed(evt);
            }
        });

        campoNomeCadastro4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro4.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro4.setText("Preço");
        campoNomeCadastro4.setBorder(new javax.swing.border.MatteBorder(null));

        textoQuantidadeProdutoPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoQuantidadeProdutoPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoQuantidadeProdutoPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoQuantidadeProdutoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQuantidadeProdutoPdvActionPerformed(evt);
            }
        });
        textoQuantidadeProdutoPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoQuantidadeProdutoPdvKeyPressed(evt);
            }
        });

        campoNomeCadastro5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro5.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro5.setText("Quantidade");
        campoNomeCadastro5.setBorder(new javax.swing.border.MatteBorder(null));

        textoPrecoProdutoPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecoProdutoPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoPrecoProdutoPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoPrecoProdutoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPrecoProdutoPdvActionPerformed(evt);
            }
        });
        textoPrecoProdutoPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoPrecoProdutoPdvKeyPressed(evt);
            }
        });

        botaoAcicionarItemPdv.setText("ADICIONAR ITEM");
        botaoAcicionarItemPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcicionarItemPdvActionPerformed(evt);
            }
        });

        botaoPesquisarProdutoPdv.setText("Pesquisar");
        botaoPesquisarProdutoPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarProdutoPdvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosProdutoPdvLayout = new javax.swing.GroupLayout(painelDadosProdutoPdv);
        painelDadosProdutoPdv.setLayout(painelDadosProdutoPdvLayout);
        painelDadosProdutoPdvLayout.setHorizontalGroup(
            painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                        .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNomeCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDescricaoProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                                .addComponent(textoIdentificadorProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(botaoPesquisarProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                        .addComponent(campoNomeCadastro4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPrecoProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNomeCadastro5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoQuantidadeProdutoPdv)))
                .addContainerGap())
            .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(botaoAcicionarItemPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDadosProdutoPdvLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoNomeCadastro, campoNomeCadastro1, campoNomeCadastro4, campoNomeCadastro5});

        painelDadosProdutoPdvLayout.setVerticalGroup(
            painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoPesquisarProdutoPdv, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(campoNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoIdentificadorProdutoPdv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNomeCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(textoDescricaoProdutoPdv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosProdutoPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeCadastro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoPrecoProdutoPdv)
                    .addGroup(painelDadosProdutoPdvLayout.createSequentialGroup()
                        .addComponent(campoNomeCadastro5, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(textoQuantidadeProdutoPdv, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(botaoAcicionarItemPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelDadosClientePdv.setBackground(new java.awt.Color(204, 204, 255));
        painelDadosClientePdv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        campoNomeCadastro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro2.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro2.setText("Nome");
        campoNomeCadastro2.setBorder(new javax.swing.border.MatteBorder(null));

        textoIdentificadorClientePdv.setBackground(new java.awt.Color(255, 255, 255));
        textoIdentificadorClientePdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoIdentificadorClientePdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoIdentificadorClientePdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIdentificadorClientePdvActionPerformed(evt);
            }
        });
        textoIdentificadorClientePdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoIdentificadorClientePdvKeyPressed(evt);
            }
        });

        campoNomeCadastro3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNomeCadastro3.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeCadastro3.setText("Data");
        campoNomeCadastro3.setBorder(new javax.swing.border.MatteBorder(null));

        textoNomeClientePdv.setEditable(false);
        textoNomeClientePdv.setBackground(new java.awt.Color(255, 255, 255));
        textoNomeClientePdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNomeClientePdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoNomeClientePdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeClientePdvActionPerformed(evt);
            }
        });
        textoNomeClientePdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoNomeClientePdvKeyPressed(evt);
            }
        });

        botaoPesquisarClientePdv.setText("Pesquisar");
        botaoPesquisarClientePdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarClientePdvActionPerformed(evt);
            }
        });

        campoIdentificadorClientePdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoIdentificadorClientePdv.setForeground(new java.awt.Color(0, 0, 0));
        campoIdentificadorClientePdv.setText("Identificador");
        campoIdentificadorClientePdv.setBorder(new javax.swing.border.MatteBorder(null));

        textoDataPdv.setEditable(false);
        textoDataPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoDataPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoDataPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoDataPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataPdvActionPerformed(evt);
            }
        });
        textoDataPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDataPdvKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosClientePdvLayout = new javax.swing.GroupLayout(painelDadosClientePdv);
        painelDadosClientePdv.setLayout(painelDadosClientePdvLayout);
        painelDadosClientePdvLayout.setHorizontalGroup(
            painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosClientePdvLayout.createSequentialGroup()
                .addGroup(painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeCadastro2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(campoNomeCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNomeClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDataPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(painelDadosClientePdvLayout.createSequentialGroup()
                .addComponent(campoIdentificadorClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoIdentificadorClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisarClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDadosClientePdvLayout.setVerticalGroup(
            painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosClientePdvLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPesquisarClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoIdentificadorClientePdv, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(textoIdentificadorClientePdv, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCadastro2)
                    .addComponent(textoNomeClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClientePdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCadastro3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(textoDataPdv, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelDadosClientePdvLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNomeCadastro2, campoNomeCadastro3});

        painelCarrinhoDeComprasPdv.setBackground(new java.awt.Color(255, 204, 204));
        painelCarrinhoDeComprasPdv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ident.", "Produto", "Qtd", "Preço", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaItensVenda);
        if (tabelaItensVenda.getColumnModel().getColumnCount() > 0) {
            tabelaItensVenda.getColumnModel().getColumn(0).setPreferredWidth(12);
            tabelaItensVenda.getColumnModel().getColumn(2).setPreferredWidth(12);
            tabelaItensVenda.getColumnModel().getColumn(3).setPreferredWidth(30);
            tabelaItensVenda.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        javax.swing.GroupLayout painelCarrinhoDeComprasPdvLayout = new javax.swing.GroupLayout(painelCarrinhoDeComprasPdv);
        painelCarrinhoDeComprasPdv.setLayout(painelCarrinhoDeComprasPdvLayout);
        painelCarrinhoDeComprasPdvLayout.setHorizontalGroup(
            painelCarrinhoDeComprasPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        painelCarrinhoDeComprasPdvLayout.setVerticalGroup(
            painelCarrinhoDeComprasPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCarrinhoDeComprasPdvLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelTotalVendaPdv.setBackground(new java.awt.Color(255, 255, 204));
        painelTotalVendaPdv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        campoTotalVendaPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTotalVendaPdv.setForeground(new java.awt.Color(0, 0, 0));
        campoTotalVendaPdv.setText("  Total de Venda");
        campoTotalVendaPdv.setBorder(new javax.swing.border.MatteBorder(null));

        textoCampoTotalVendaPdv.setBackground(new java.awt.Color(255, 255, 255));
        textoCampoTotalVendaPdv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoCampoTotalVendaPdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoCampoTotalVendaPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCampoTotalVendaPdvActionPerformed(evt);
            }
        });
        textoCampoTotalVendaPdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoCampoTotalVendaPdvKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelTotalVendaPdvLayout = new javax.swing.GroupLayout(painelTotalVendaPdv);
        painelTotalVendaPdv.setLayout(painelTotalVendaPdvLayout);
        painelTotalVendaPdvLayout.setHorizontalGroup(
            painelTotalVendaPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotalVendaPdvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoTotalVendaPdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoCampoTotalVendaPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelTotalVendaPdvLayout.setVerticalGroup(
            painelTotalVendaPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotalVendaPdvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTotalVendaPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTotalVendaPdv, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(textoCampoTotalVendaPdv))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoPagamentoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCancelarVendaPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelDadosClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelDadosProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelCarrinhoDeComprasPdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelTotalVendaPdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCarrinhoDeComprasPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelTotalVendaPdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelDadosClientePdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelDadosProdutoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCancelarVendaPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPagamentoPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date agora = new Date();
        SimpleDateFormat formatoBr = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = formatoBr.format(agora);
        textoDataPdv.setText(dataFormatada);
    }//GEN-LAST:event_formWindowActivated

    private void textoDescricaoProdutoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDescricaoProdutoPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescricaoProdutoPdvActionPerformed

    private void textoDescricaoProdutoPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDescricaoProdutoPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescricaoProdutoPdvKeyPressed

    private void textoIdentificadorProdutoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIdentificadorProdutoPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdentificadorProdutoPdvActionPerformed

    private void textoIdentificadorProdutoPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIdentificadorProdutoPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdentificadorProdutoPdvKeyPressed

    private void textoIdentificadorClientePdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIdentificadorClientePdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdentificadorClientePdvActionPerformed

    private void textoIdentificadorClientePdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIdentificadorClientePdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdentificadorClientePdvKeyPressed

    private void textoNomeClientePdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeClientePdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeClientePdvActionPerformed

    private void textoNomeClientePdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNomeClientePdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeClientePdvKeyPressed

    private void textoQuantidadeProdutoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQuantidadeProdutoPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoQuantidadeProdutoPdvActionPerformed

    private void textoQuantidadeProdutoPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoQuantidadeProdutoPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoQuantidadeProdutoPdvKeyPressed

    private void textoPrecoProdutoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrecoProdutoPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrecoProdutoPdvActionPerformed

    private void textoPrecoProdutoPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoPrecoProdutoPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrecoProdutoPdvKeyPressed

    private void textoCampoTotalVendaPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCampoTotalVendaPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCampoTotalVendaPdvActionPerformed

    private void textoCampoTotalVendaPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoCampoTotalVendaPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCampoTotalVendaPdvKeyPressed

    /**
     * procura um cliente pelo seu id e insere no campo nomeCliente no PDV
     * @param evt
     */
    private void botaoPesquisarClientePdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarClientePdvActionPerformed
        // TODO add your handling code here:
        ClienteDao dao = new ClienteDao();
        clienteVendaView = dao.buscarClientePorId(textoIdentificadorClientePdv.getText());
        textoNomeClientePdv.setText(clienteVendaView.getNome());
    }//GEN-LAST:event_botaoPesquisarClientePdvActionPerformed

    private void textoDataPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataPdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataPdvActionPerformed

    private void textoDataPdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDataPdvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataPdvKeyPressed

    /**
     * Este método é executado quando o botão "Adicionar Item" é pressionado no contexto de uma tela de ponto de venda (PDV).
     * Ele permite gerenciar o carrinho de compras, também verificando se existe estoque disponível do produto a cada tentativa
     * de inserção de um novo produto no carrinho. Caso o produto tenha estoque disponível, a inserção é realizada.
     * Um mesmo produto não pode ser adicionado em dois registros diferente do carrinho, nesse caso, atualizamos somente a quantidade.
     *
     * @param evt O evento que desencadeou a ação do botão.
     */
    private void botaoAcicionarItemPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcicionarItemPdvActionPerformed
        botaoPesquisarClientePdv.setVisible(false);
        botaoPesquisarProdutoPdv.doClick();

        Integer id = Integer.parseInt(textoIdentificadorProdutoPdv.getText());
        quantidade = Integer.parseInt(textoQuantidadeProdutoPdv.getText());

        if (verificaSeTemEstoqueDisponivel(id, quantidade)) {

            preco = new BigDecimal(textoPrecoProdutoPdv.getText());
            subtotal = preco.multiply(BigDecimal.valueOf(quantidade));
            total = total.add(subtotal);
            textoCampoTotalVendaPdv.setText(total.toString());

            carrinhoDeComprasVendaView = (DefaultTableModel) tabelaItensVenda.getModel();
            String identificadorProduto = textoIdentificadorProdutoPdv.getText();
            boolean identificadorExistente = false;

            for (int i = 0; i < carrinhoDeComprasVendaView.getRowCount(); i++) {
                String identificadorSendoVerificado = (String) carrinhoDeComprasVendaView.getValueAt(i, 0).toString();

                if (identificadorSendoVerificado.equals(identificadorProduto)) {
                    Integer quantidadeExistente = (Integer) carrinhoDeComprasVendaView.getValueAt(i, 2);
                    BigDecimal subtotalExistente = (BigDecimal) carrinhoDeComprasVendaView.getValueAt(i, 4);

                    quantidadeExistente += quantidade;

                    if (verificaSeTemEstoqueDisponivel(id, quantidadeExistente)) {
                        subtotalExistente = subtotalExistente.add(subtotal);

                        carrinhoDeComprasVendaView.setValueAt(quantidadeExistente, i, 2);
                        carrinhoDeComprasVendaView.setValueAt(subtotalExistente, i, 4);

                        identificadorExistente = true;
                        break;
                    }
                    else {
                        total = total.subtract(subtotal);
                        textoCampoTotalVendaPdv.setText(total.toString());
                        return;
                    }
                }
            }

            if (!identificadorExistente) {
                carrinhoDeComprasVendaView.addRow(new Object[]{
                        identificadorProduto,
                        textoDescricaoProdutoPdv.getText(),
                        quantidade,
                        textoPrecoProdutoPdv.getText(),
                        subtotal
                });
            }
        }

    }//GEN-LAST:event_botaoAcicionarItemPdvActionPerformed

    private void botaoPesquisarProdutoPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarProdutoPdvActionPerformed
        ProdutoDao dao = new ProdutoDao();
        Produto produto = dao.buscarProdutoPorId(textoIdentificadorProdutoPdv.getText());
        textoDescricaoProdutoPdv.setText(produto.getDescricao());
        textoPrecoProdutoPdv.setText(produto.getPreco().toString());
    }//GEN-LAST:event_botaoPesquisarProdutoPdvActionPerformed

    private void botaoPagamentoPdvActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        PagamentosView pagamentosView = new PagamentosView();
        pagamentosView.textoTotalPagamento.setText(total.toString());
        pagamentosView.clientePagamentoView = clienteVendaView;
        pagamentosView.carrinhoDeComprasPagamentoView = carrinhoDeComprasVendaView;
        pagamentosView.setVisible(true);
        this.dispose();
    }

    /**
     * botão que fecha o PDV e cancela a montagem de uma venda
     * @param evt
     */
    private void botaoCancelarVendaPdvActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int op;
        op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar essa venda?");
        if (op == 0) {
            this.dispose();
        }
    }

    /**
     * Verifica se há estoque disponível para atender a uma solicitação de um produto.
     *
     * @param idProduto           O ID do produto que está sendo verificado.
     * @param quantidadeSolicitada A quantidade desejada do produto.
     * @return                    {@code true} se houver estoque disponível para atender ao pedido;
     *                            {@code false} caso contrário, exibindo uma mensagem de aviso.
     */
    public boolean verificaSeTemEstoqueDisponivel(Integer idProduto, Integer quantidadeSolicitada) {
        ProdutoDao produtoDao = new ProdutoDao();
        Integer estoqueAtual = produtoDao.retornaEstoqueAtual(idProduto);

        if (estoqueAtual < quantidadeSolicitada) {
            JOptionPane.showMessageDialog(null, "A quantidade em estoque deste produto é insuficiente para atender seu pedido." +
                    "\nEstoque atual: " + estoqueAtual + " unidades");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcicionarItemPdv;
    private javax.swing.JButton botaoCancelarVendaPdv;
    private javax.swing.JButton botaoPagamentoPdv;
    private javax.swing.JButton botaoPesquisarClientePdv;
    private javax.swing.JButton botaoPesquisarProdutoPdv;
    private javax.swing.JLabel campoIdentificadorClientePdv;
    private javax.swing.JLabel campoNomeCadastro;
    private javax.swing.JLabel campoNomeCadastro1;
    private javax.swing.JLabel campoNomeCadastro2;
    private javax.swing.JLabel campoNomeCadastro3;
    private javax.swing.JLabel campoNomeCadastro4;
    private javax.swing.JLabel campoNomeCadastro5;
    private javax.swing.JLabel campoTotalVendaPdv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelCarrinhoDeComprasPdv;
    private javax.swing.JPanel painelDadosClientePdv;
    private javax.swing.JPanel painelDadosProdutoPdv;
    private javax.swing.JPanel painelTotalVendaPdv;
    public javax.swing.JTable tabelaItensVenda;
    private javax.swing.JTextField textoCampoTotalVendaPdv;
    private javax.swing.JTextField textoDataPdv;
    private javax.swing.JTextField textoDescricaoProdutoPdv;
    private javax.swing.JTextField textoIdentificadorClientePdv;
    private javax.swing.JTextField textoIdentificadorProdutoPdv;
    private javax.swing.JTextField textoNomeClientePdv;
    private javax.swing.JTextField textoPrecoProdutoPdv;
    private javax.swing.JTextField textoQuantidadeProdutoPdv;
    // End of variables declaration//GEN-END:variables
}
